### PR TITLE
Brightness, Governor, Telephony

### PR DESCRIPTION
**Pull request by mickybart**
Add Adaptive brightness (dark screen fixed)
Ambient display minimun brightness
Disable Dreams (when dozeComponent defined)

### CODE REVIEW

**Comment by billchen1977** [comment]
are you sure Adaptive brightness work well? the light sensor can't give us a accurate Lux, and maybe vary between devices.
I'm not sure dreams should be disable, because doze can be disable by setting.

**Comment by mickybart** [comment]
For Adpative brightness I'm using it since a while and some others on other ROM use it too without any trouble. It's right that it's not easy to set good range lux/brightness but the current settings seems not so bad (come from FXP, OpenSEmc etc). One of the good point of Android 5 is that the user can change the brightness to lower or higher value to change the Adaptive brightness settings. With that possiblity the final user can adjust the behaviour and so depending lux detector etc he can easly have a better configuration.
When the Adaptive brightness is enable and the brigthness control is on the middle you have the base settings (the one provided on this patch).

About dreams, this is what is suggested by Google on AOSP on the config.xml : 

Specifies whether the dreams feature should be supported.
         When true, the system will allow the user to configure dreams (screensavers)
         to launch when a user activity timeout occurs or the system is told to nap.
         When false, the dreams feature will be disabled (this does not affect dozing).

```
     Consider setting this resource to false or disabling dreams by default when a
     doze component is specified below since dreaming will supercede dozing and
     will prevent the system from entering a low power state until the dream ends.
```

**Comment by billchen1977** [comment]
Thank your description.
For Adpative brightness, I remember in OpenSEMC, the LUX value return from sensor is modified. I'll try.

**Comment by mickybart** [comment]
Ok I will let you try and give me your advise. Thanks for you help and interest.

**Comment by mickybart** [comment]
Those 2 commits are for Adaptive brightness and for Buttons backlight brightness. That will avoid to have lightbar too brighter (255). By default the lightbar brightness will take the level of the screen (as it is set on the frameworks/base code)

**Comment by mickybart** [comment]
This one is to have a better response time when environment become brighter.

**Comment by mickybart** [comment]
This patch is to permit to set by default another governor than ondemand.
Without it, ondemand will be always used after the boot. So the script check if the governor is ondemand and if it is the case, it set ondemand parameters.

**Comment by mickybart** [comment]
The patch telephony permit to re-enable every fonctions. It's possible to do conference call for example. RIL should be ready for EAP-SIM but not yet tested.

Adapation done for QCOM SIM not ready like the Nozomi.

**Pull request closed without merging**
